services:
    cse.customer.manager:
        class: AppBundle\Manager\CustomerManager
        calls:
            - [ 'setUserFromSecurityContext', [ '@security.token_storage' ]]
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ]]
            - [ 'setProviderFactory', [ '@cse.provider.factory' ]]