<?php

namespace AppBundle\Repository;

/**
 * MailListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailListRepository extends \Doctrine\ORM\EntityRepository
{
}
