# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    roles:
        ROLE_SUPER_ADMIN : [ROLE_ADMIN]
        ROLE_RESPONSABLE_AGENCE : [ROLE_COMMERCIAL]
        ROLE_ADMIN : [ROLE_RESPONSABLE_AGENCE,ROLE_COMMERCIAL]
        ROLE_COMMERCIAL : []
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
