# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    app.mail_notifier:
#        class: AppBundle\Services\MailNotifierService
#        arguments: ["@mailer", "@logger"]
#    app.csv_parser:
#        class: AppBundle\Services\CsvFileParserService
#    app.file_upload_handler:
#        class: AppBundle\Handlers\FileUploadHandler
#        arguments:
#            - '%parsed_files_directory%'
    app.evaluation_service:
        class: AppBundle\Services\EvaluationService
        arguments:
            - '@doctrine.orm.entity_manager'
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
