<?php

namespace UserBundle\Repository;

/**
 * CollaboraterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaboraterRepository extends \Doctrine\ORM\EntityRepository
{
}
