sf_security:
    resource: "@UserBundle/Resources/config/security.yml"

user_list:
    path:     /user-list
    defaults: { _controller: UserBundle:User:index }

#user_homepage:
#    path:     /user
#    defaults: { _controller: UserBundle:User:index }
